import { z } from "zod";

/**
 * Structured content for a project proposal PDF — generated by AI (see
 * /api/empresa/projects/[id]/ai-expand-proposal) and persisted on Project.proposalContent.
 * The proposal template (templates/proyecto-propuesta-pdf.tsx) renders exactly this shape.
 *
 * Backed by a zod schema (not just a shallow type guard) so a malformed/truncated AI response is
 * rejected before it ever reaches the PDF renderer — a missing `phases[].price` or empty
 * `scopeIncludes` array should fail loudly in the API route, not render a broken page.
 */
export const proposalPhaseSchema = z.object({
  tag: z.string().min(1),
  isFirstPhase: z.boolean(),
  name: z.string().min(1),
  price: z.string().min(1),
  timeframe: z.string().min(1),
  body: z.string().min(1),
  footerLabel: z.string().min(1),
});

export const proposalContentSchema = z.object({
  pillars: z.array(z.string().min(1)).min(2).max(4),
  whatWereBuilding: z.string().min(1),
  whyThisApproach: z.string().min(1),
  contextObjective: z.string().min(1),
  architecture: z.object({
    frontend: z.string().min(1),
    backend: z.string().min(1),
    infra: z.string().min(1),
    attributes: z.array(z.string().min(1)).min(1),
  }),
  phases: z.array(proposalPhaseSchema).min(1).max(6),
  scopeIncludes: z.array(z.string().min(1)).min(1),
  scopeExcludes: z.array(z.string().min(1)).min(1),
  investmentNote: z.string().min(1),
  closingSteps: z.array(z.object({ title: z.string().min(1), description: z.string().min(1) })).min(1),
});

export type ProposalPhase = z.infer<typeof proposalPhaseSchema>;
export type ProposalContent = z.infer<typeof proposalContentSchema>;

export function isProposalContent(value: unknown): value is ProposalContent {
  return proposalContentSchema.safeParse(value).success;
}

/** Same check as isProposalContent, but returns the zod issues for surfacing a real error message. */
export function parseProposalContent(value: unknown) {
  return proposalContentSchema.safeParse(value);
}
