import type { Project } from "./types";

/** Tiendas, sitios de marca y experiencias. */
export const siteProjects: Project[] = [
  {
    slug: "misaza",
    name: "Misaza",
    client: "Misaza",
    industry: "Retail y moda",
    tagline: "E-commerce panameño reescrito desde cero: variantes, Yappy, PayPal y CMS.",
    description:
      "Catálogo con tallas, colores y nueve parámetros de URL, precios con ITBMS y mayorista desde una sola fuente, reserva blanda de stock que se descuenta al pagar, pedido especial cuando no hay inventario, citas con clientes y un CMS de catorce secciones. Trece mil redirecciones 301 conservan el SEO de la tienda anterior en Vue.",
    category: "ecommerce",
    status: "construccion",
    years: [2024, 2026],
    stack: ["Next.js 15", "Supabase", "Yappy", "PayPal", "Resend", "Cloudflare R2", "Vitest", "Playwright"],
    features: [
      "Catálogo con relevancia, conteos y variantes",
      "Reserva de stock, descuento al pagar y restitución",
      "Yappy con IPN verificada y PayPal con webhook",
      "Pedido especial sin inventario",
      "Citas con capacidad, horarios y reprogramación",
      "Kardex, cola de correos y rate limiting en Postgres",
    ],
    routes: [
      { path: "/", label: "Tienda", group: "publico", screen: "store" },
      { path: "/explore", label: "Explorar catálogo", group: "publico", screen: "store" },
      { path: "/product/[id]", label: "Producto", group: "publico", screen: "store" },
      { path: "/checkout", label: "Pago", group: "publico", screen: "checkout" },
      { path: "/mayoreo", label: "Mayoreo", group: "publico", screen: "form" },
      { path: "/admin", label: "CMS", group: "panel", screen: "dashboard" },
      { path: "/api/pagos/yappy/ipn", label: "IPN Yappy", group: "api", screen: "terminal" },
      { path: "/api/kardex", label: "Kardex", group: "api", screen: "table" },
    ],
    liveUrl: "https://misaza.com",
    demoUrl: null,
    brand: { primary: "#111111", secondary: "#c9a227", surface: "#ffffff", ink: "#111111", scheme: "light" },
    screen: "store",
    metrics: [
      { key: "orders", label: "Pedidos", unit: "pedidos", base: 640, growth: 0.05, form: "bars" },
      { key: "revenue", label: "Ventas", unit: "USD", base: 38000, growth: 0.04, form: "area" },
    ],
    featured: true,
    variants: ["Misaza (Vue 3 + Vite, legacy)", "apexV2-platform (CMS Vue, legacy)", "apexV2-api (Flask, legacy)"],
  },
  {
    slug: "bright-tale-store",
    name: "Bright Tale Store",
    client: "Autores y creadores",
    industry: "Productos digitales",
    tagline: "Tienda de libros, cursos y descargables con CMS por bloques.",
    description:
      "El frontend público se arma desde un registro de bloques editables en el admin, con esquemas Zod que generan los formularios automáticamente. Storefront, checkout, biblioteca del comprador y admin de productos, pedidos y clientes.",
    category: "ecommerce",
    status: "prototipo",
    years: [2025, 2026],
    stack: ["Next.js 16", "Supabase", "Cloudflare R2", "Zod", "date-fns"],
    features: [
      "Storefront de libros y cursos",
      "Checkout con éxito y cancelación",
      "Biblioteca y pedidos por usuario",
      "CMS por bloques con formularios generados",
      "Admin de productos, pedidos, clientes y media",
    ],
    routes: [
      { path: "/books", label: "Libros", group: "publico", screen: "store" },
      { path: "/books/[slug]", label: "Ficha", group: "publico", screen: "store" },
      { path: "/checkout", label: "Pago", group: "publico", screen: "checkout" },
      { path: "/account/library", label: "Biblioteca", group: "publico", screen: "table" },
      { path: "/admin/content", label: "Bloques", group: "panel", screen: "docs" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#111827", secondary: "#f59e0b", surface: "#f5f5f4", ink: "#111827", scheme: "light" },
    screen: "store",
    metrics: [
      { key: "downloads", label: "Descargas", unit: "descargas", base: 900, growth: 0.06, form: "bars" },
      { key: "readers", label: "Lectores", unit: "cuentas", base: 340, growth: 0.05, form: "area" },
    ],
    featured: false,
  },
  {
    slug: "bnb-real-estate",
    name: "B&B Real Estate",
    client: "B&B Real Estate",
    industry: "Bienes raíces",
    tagline: "Inmobiliaria trilingüe pensada para el inversionista extranjero.",
    description:
      "Sitio en español, inglés y portugués con catálogo sincronizado desde Wasi, proyectos en preconstrucción, mapas con clustering y captación de propietarios. CMS interno con inventario, leads y campañas, y un módulo restringido de verificación documental sobre R2 con RLS.",
    category: "sitio",
    status: "produccion",
    years: [2025, 2026],
    stack: ["Next.js", "Supabase", "Cloudflare R2", "Google Maps", "Wasi MLS", "Playwright"],
    features: [
      "Trilingüe con sitemaps por idioma y llms.txt",
      "Catálogo y preconstrucción con mapas",
      "Sincronización de inventario con Wasi",
      "CMS de inventario, contenido, leads y campañas",
      "Verificación documental de clientes",
      "Pipeline de imágenes con variantes y auditoría",
    ],
    routes: [
      { path: "/", label: "Landing", group: "publico", screen: "landing" },
      { path: "/propiedades", label: "Propiedades", group: "publico", screen: "store" },
      { path: "/proyectos", label: "Preconstrucción", group: "publico", screen: "map" },
      { path: "/list-with-us", label: "Publica tu propiedad", group: "publico", screen: "form" },
      { path: "/cms", label: "CMS", group: "panel", screen: "dashboard" },
      { path: "/portal", label: "Portal de cliente", group: "panel", screen: "docs" },
    ],
    liveUrl: "https://bbrealestate.com.pa",
    demoUrl: "/portfolio/demos/bnb-real-estate",
    brand: { primary: "#111111", secondary: "#f2c94c", surface: "#ffffff", ink: "#111111", scheme: "light" },
    screen: "landing",
    metrics: [
      { key: "leads", label: "Leads calificados", unit: "leads", base: 85, growth: 0.06, form: "bars" },
      { key: "listings", label: "Propiedades publicadas", unit: "listados", base: 420, growth: 0.02, form: "area" },
    ],
    featured: true,
  },
  {
    slug: "holo-realty",
    name: "HOLO Realty",
    client: "HOLO Realty & Relocation",
    industry: "Bienes raíces y relocation",
    tagline: "Venta, alquiler, relocation e inversión con un portal de cliente en tiempo real.",
    description:
      "Rebrand sobre la misma base inmobiliaria: el diferencial es un portal donde el cliente ve su progreso, acepta o rechaza decisiones y sigue hitos en tiempo real. El CRM interno cubre pipeline configurable, finanzas, expedientes de relocation y edificios con contratos e inspecciones.",
    category: "sitio",
    status: "beta",
    years: [2025, 2026],
    stack: ["Next.js 15", "Supabase Realtime", "Cloudflare R2", "Tailwind v4", "Wasi MLS"],
    features: [
      "Portal de cliente con progreso y decisiones",
      "CRM con bitácora de interacciones",
      "Pipeline no-code configurable",
      "Relocation con expedientes y checklists",
      "Edificios: unidades, contratos, inspecciones",
      "Inventario conmutable entre Wasi y CMS",
    ],
    routes: [
      { path: "/", label: "Landing", group: "publico", screen: "landing" },
      { path: "/relocation", label: "Relocation", group: "publico", screen: "docs" },
      { path: "/propiedades", label: "Propiedades", group: "publico", screen: "store" },
      { path: "/portal", label: "Portal de cliente", group: "panel", screen: "dashboard" },
      { path: "/cms/crm", label: "CRM", group: "panel", screen: "table" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#1e293b", secondary: "#38bdf8", surface: "#f8fafc", ink: "#0f172a", scheme: "light" },
    screen: "dashboard",
    metrics: [
      { key: "cases", label: "Expedientes activos", unit: "casos", base: 34, growth: 0.05, form: "area" },
      { key: "milestones", label: "Hitos cerrados", unit: "hitos", base: 120, growth: 0.06, form: "bars" },
    ],
    featured: false,
  },
  {
    slug: "john-henry",
    name: "John Henry Oficial",
    client: "John Henry Tailoring",
    industry: "Sastrería de lujo",
    tagline: "Marca de sastrería con sedes en Bogotá y Panamá, y su taller en un CMS.",
    description:
      "Sitio editorial con el oficio, ready-to-wear y agenda de citas sincronizada con Google Calendar. Detrás, un CRM con clientes y medidas, órdenes de taller imprimibles, catálogo de telas y modelos, y finanzas con regalías y comisiones de asesores. PWA con modo offline.",
    category: "sitio",
    status: "produccion",
    years: [2026],
    stack: ["Next.js 16", "Supabase", "Google Calendar", "React Three Fiber", "Cloudflare R2", "Turnstile", "Recharts"],
    features: [
      "Landing editorial con sedes y citas",
      "CRM con ficha de medidas e historial",
      "Órdenes de taller imprimibles",
      "Catálogo de telas y modelos con fotos",
      "Finanzas: cobros, regalías y comisiones",
      "Plantillas de correo editables",
    ],
    routes: [
      { path: "/", label: "Landing", group: "publico", screen: "landing" },
      { path: "/citas", label: "Agendar cita", group: "publico", screen: "calendar" },
      { path: "/ready-to-wear", label: "Ready-to-wear", group: "publico", screen: "store" },
      { path: "/clients/[id]/medidas", label: "Medidas", group: "panel", screen: "form" },
      { path: "/orders/[id]/orden-taller", label: "Orden de taller", group: "operacion", screen: "docs" },
      { path: "/finance/reportes", label: "Reportes", group: "panel", screen: "dashboard" },
    ],
    liveUrl: "https://www.johnhenryoficial.com",
    demoUrl: null,
    brand: { primary: "#c4a55a", secondary: "#e8d090", surface: "#0e1a2b", ink: "#f4efe2", scheme: "dark" },
    screen: "landing",
    metrics: [
      { key: "orders", label: "Órdenes de taller", unit: "órdenes", base: 48, growth: 0.04, form: "bars" },
      { key: "appointments", label: "Citas", unit: "citas", base: 90, growth: 0.05, form: "area" },
    ],
    featured: true,
  },
  {
    slug: "chivas-parranderas",
    name: "Chivas Parranderas",
    client: "Chivas Parranderas Panamá",
    industry: "Turismo y entretenimiento",
    tagline: "Reservas de fiestas privadas en bus: paquetes, galería y admin.",
    description:
      "Landing de lujo con paquetes destacados desde Supabase, galería, FAQ y formulario de leads con WhatsApp. Flujo de reserva y panel de productos y reservas. Marca centralizada en un archivo de configuración y JSON-LD de negocio local.",
    category: "sitio",
    status: "prototipo",
    years: [2026],
    stack: ["Next.js 16", "Supabase", "Cloudflare R2", "Zod", "JSON-LD"],
    features: [
      "Hero con CTA y WhatsApp",
      "Paquetes destacados desde Supabase",
      "Galería y FAQ",
      "Flujo de reserva",
      "Admin de productos y reservas",
    ],
    routes: [
      { path: "/", label: "Landing", group: "publico", screen: "landing" },
      { path: "/book", label: "Reservar", group: "publico", screen: "checkout" },
      { path: "/admin/products", label: "Paquetes", group: "panel", screen: "table" },
      { path: "/admin/reservations", label: "Reservas", group: "panel", screen: "calendar" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#c9a227", secondary: "#b84d8e", surface: "#050508", ink: "#f7edd2", scheme: "dark" },
    screen: "landing",
    metrics: [
      { key: "bookings", label: "Reservas", unit: "reservas", base: 22, growth: 0.07, form: "bars" },
      { key: "leads", label: "Leads", unit: "leads", base: 70, growth: 0.06, form: "area" },
    ],
    featured: false,
  },
  {
    slug: "mision-cristiana",
    name: "Misión Cristiana",
    client: "Misión Cristiana",
    industry: "Organizaciones religiosas",
    tagline: "Sitio institucional de una iglesia: bienvenida, video y ministerios.",
    description:
      "Página única con animaciones al scroll, video institucional, ministerios y redes sociales. Sin backend: build estático con Vue y Vite. Es el proyecto más antiguo del catálogo y sigue recibiendo retoques.",
    category: "sitio",
    status: "produccion",
    years: [2023, 2026],
    stack: ["Vue 3", "Vite", "Bootstrap 5", "AOS"],
    features: [
      "Landing de una página con animaciones",
      "Video institucional",
      "Sección de ministerios",
      "Botones de redes sociales",
    ],
    routes: [{ path: "/", label: "Inicio", group: "publico", screen: "landing" }],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#7c2d12", secondary: "#d6b370", surface: "#fffdf8", ink: "#2b1a12", scheme: "light" },
    screen: "landing",
    metrics: [
      { key: "visits", label: "Visitas", unit: "visitas", base: 1400, growth: 0.02, form: "area" },
      { key: "contacts", label: "Contactos", unit: "mensajes", base: 12, growth: 0.03, form: "bars" },
    ],
    featured: false,
  },
  {
    slug: "muro-anatolia",
    name: "Muro Anatolia",
    client: "Activación de marca",
    industry: "Marketing y gaming",
    tagline: "Juego 3D de penales en WebGL para una campaña bancaria.",
    description:
      "El jugador ataja penales desde la cámara del arquero con física en metros reales y arco reglamentario FIFA dividido en nueve zonas. Cinco niveles, audio, móvil-first y sin backend. Motor propio sobre Three.js.",
    category: "juego",
    status: "produccion",
    years: [2025],
    stack: ["Three.js", "Vite", "WebGL", "JavaScript"],
    features: [
      "Motor 3D con física en metros",
      "Arco de nueve zonas y cinco niveles",
      "Medidas FIFA reales",
      "Audio y assets de balón",
      "Branding de campaña con glassmorphism",
    ],
    routes: [{ path: "/", label: "Jugar", group: "publico", screen: "game" }],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#ffe600", secondary: "#8b5cf6", surface: "#050505", ink: "#fffbe6", scheme: "dark" },
    screen: "game",
    metrics: [
      { key: "sessions", label: "Sesiones de juego", unit: "sesiones", base: 8200, growth: 0.04, form: "bars" },
      { key: "saves", label: "Atajadas", unit: "atajadas", base: 21000, growth: 0.04, form: "area" },
    ],
    featured: false,
  },
  {
    slug: "country-card-game",
    name: "Country Card Game",
    client: "Anita Gawecka",
    industry: "Juegos de mesa",
    tagline: "Compañero digital bilingüe de un juego de cartas de países.",
    description:
      "Propuesta comercial: guía interactiva de países con animación de volteo, motor de quiz cronometrado, registro por correo, portal de suscriptores con export y PWA instalable sin app store. Sin licencias recurrentes.",
    category: "propuesta",
    status: "propuesta",
    years: [2026],
    stack: ["Next.js", "Supabase", "PWA"],
    features: [
      "Guía interactiva de países con volteo de carta",
      "Quiz con temporizador y rondas bonus",
      "Registro por correo sin login",
      "Portal admin con métricas y export CSV",
      "PWA instalable en iOS y Android",
    ],
    routes: [
      { path: "/countries", label: "Guía", group: "publico", screen: "store" },
      { path: "/quiz", label: "Quiz", group: "publico", screen: "game" },
      { path: "/admin", label: "Suscriptores", group: "panel", screen: "table" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#0f766e", secondary: "#f97316", surface: "#f0fdfa", ink: "#134e4a", scheme: "light" },
    screen: "game",
    metrics: [
      { key: "quizzes", label: "Quizzes completados", unit: "quizzes", base: 600, growth: 0.08, form: "bars" },
      { key: "subs", label: "Suscriptores", unit: "personas", base: 250, growth: 0.07, form: "area" },
    ],
    featured: false,
  },
  {
    slug: "roblox-sandbox",
    name: "Roblox Sandbox",
    client: null,
    industry: "Gaming",
    tagline: "Mundo acuático procedural en Roblox con botes y NPCs.",
    description:
      "Prototipo de exploración técnica sincronizado con Rojo: agua e islas generadas por procedimiento, botes manejables con input cliente-servidor, NPCs y sistema de animaciones.",
    category: "juego",
    status: "prototipo",
    years: [2026],
    stack: ["Luau", "Rojo", "Roblox Studio"],
    features: [
      "Generación procedural de agua e islas",
      "Botes con abordaje y control",
      "Input cliente-servidor por RemoteEvents",
      "Spawner de NPCs y billboards",
    ],
    routes: [{ path: "/", label: "Mundo", group: "publico", screen: "game" }],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#38bdf8", secondary: "#fde047", surface: "#082f49", ink: "#e0f2fe", scheme: "dark" },
    screen: "game",
    metrics: [
      { key: "islands", label: "Islas generadas", unit: "islas", base: 300, growth: 0.05, form: "bars" },
      { key: "players", label: "Jugadores", unit: "jugadores", base: 40, growth: 0.06, form: "area" },
    ],
    featured: false,
  },
];
