import type { Project } from "./types";

/** Tiendas, sitios de marca y experiencias. */
export const siteProjects: Project[] = [
  {
    slug: "misaza",
    name: "Misaza",
    client: "Misaza",
    industry: "Retail y moda",
    tagline: "E-commerce panameño reescrito desde cero: variantes, Yappy, PayPal y CMS.",
    description:
      "Catálogo con tallas, colores y nueve parámetros de URL, precios con ITBMS y mayorista desde una sola fuente, reserva blanda de stock que se descuenta al pagar, pedido especial cuando no hay inventario, citas con clientes y un CMS de catorce secciones. Trece mil redirecciones 301 conservan el SEO de la tienda anterior en Vue.",
    category: "ecommerce",
    status: "construccion",
    years: [2024, 2026],
    stack: ["Next.js 15", "Supabase", "Yappy", "PayPal", "Resend", "Cloudflare R2", "Vitest", "Playwright"],
    features: [
      "Catálogo con relevancia, conteos y variantes",
      "Reserva de stock, descuento al pagar y restitución",
      "Yappy con IPN verificada y PayPal con webhook",
      "Pedido especial sin inventario",
      "Citas con capacidad, horarios y reprogramación",
      "Kardex, cola de correos y rate limiting en Postgres",
    ],
    routes: [
      { path: "/", label: "Tienda", group: "publico", screen: "store" },
      { path: "/explore", label: "Explorar catálogo", group: "publico", screen: "store" },
      { path: "/product/[id]", label: "Producto", group: "publico", screen: "store" },
      { path: "/checkout", label: "Pago", group: "publico", screen: "checkout" },
      { path: "/mayoreo", label: "Mayoreo", group: "publico", screen: "form" },
      { path: "/admin", label: "CMS", group: "panel", screen: "dashboard" },
      { path: "/api/pagos/yappy/ipn", label: "IPN Yappy", group: "api", screen: "terminal" },
      { path: "/api/kardex", label: "Kardex", group: "api", screen: "table" },
    ],
    liveUrl: "https://misaza.com",
    demoUrl: null,
    brand: { primary: "#111111", secondary: "#c9a227", surface: "#ffffff", ink: "#111111", scheme: "light" },
    screen: "store",
    metrics: [
      { key: "orders", label: "Pedidos", unit: "pedidos", base: 640, growth: 0.05, form: "bars" },
      { key: "revenue", label: "Ventas", unit: "USD", base: 38000, growth: 0.04, form: "area" },
    ],
    featured: true,
    variants: ["Misaza (Vue 3 + Vite, legacy)", "apexV2-platform (CMS Vue, legacy)", "apexV2-api (Flask, legacy)"],
  },
  {
    slug: "bnb-real-estate",
    name: "B&B Real Estate",
    client: "B&B Real Estate",
    industry: "Bienes raíces",
    tagline: "Inmobiliaria trilingüe pensada para el inversionista extranjero.",
    description:
      "Sitio en español, inglés y portugués con catálogo sincronizado desde Wasi, proyectos en preconstrucción, mapas con clustering y captación de propietarios. CMS interno con inventario, leads y campañas, y un módulo restringido de verificación documental sobre R2 con RLS.",
    category: "sitio",
    status: "produccion",
    years: [2025, 2026],
    stack: ["Next.js", "Supabase", "Cloudflare R2", "Google Maps", "Wasi MLS", "Playwright"],
    features: [
      "Trilingüe con sitemaps por idioma y llms.txt",
      "Catálogo y preconstrucción con mapas",
      "Sincronización de inventario con Wasi",
      "CMS de inventario, contenido, leads y campañas",
      "Verificación documental de clientes",
      "Pipeline de imágenes con variantes y auditoría",
    ],
    routes: [
      { path: "/", label: "Landing", group: "publico", screen: "landing" },
      { path: "/propiedades", label: "Propiedades", group: "publico", screen: "store" },
      { path: "/proyectos", label: "Preconstrucción", group: "publico", screen: "map" },
      { path: "/list-with-us", label: "Publica tu propiedad", group: "publico", screen: "form" },
      { path: "/cms", label: "CMS", group: "panel", screen: "dashboard" },
      { path: "/portal", label: "Portal de cliente", group: "panel", screen: "docs" },
    ],
    liveUrl: "https://bbrealestate.com.pa",
    demoUrl: "/portfolio/demos/bnb-real-estate",
    brand: { primary: "#111111", secondary: "#f2c94c", surface: "#ffffff", ink: "#111111", scheme: "light" },
    screen: "landing",
    metrics: [
      { key: "leads", label: "Leads calificados", unit: "leads", base: 85, growth: 0.06, form: "bars" },
      { key: "listings", label: "Propiedades publicadas", unit: "listados", base: 420, growth: 0.02, form: "area" },
    ],
    featured: true,
  },
  {
    slug: "john-henry",
    name: "John Henry Oficial",
    client: "John Henry Tailoring",
    industry: "Sastrería de lujo",
    tagline: "Marca de sastrería con sedes en Bogotá y Panamá, y su taller en un CMS.",
    description:
      "Sitio editorial con el oficio, ready-to-wear y agenda de citas sincronizada con Google Calendar. Detrás, un CRM con clientes y medidas, órdenes de taller imprimibles, catálogo de telas y modelos, y finanzas con regalías y comisiones de asesores. PWA con modo offline.",
    category: "sitio",
    status: "produccion",
    years: [2026],
    stack: ["Next.js 16", "Supabase", "Google Calendar", "React Three Fiber", "Cloudflare R2", "Turnstile", "Recharts"],
    features: [
      "Landing editorial con sedes y citas",
      "CRM con ficha de medidas e historial",
      "Órdenes de taller imprimibles",
      "Catálogo de telas y modelos con fotos",
      "Finanzas: cobros, regalías y comisiones",
      "Plantillas de correo editables",
    ],
    routes: [
      { path: "/", label: "Landing", group: "publico", screen: "landing" },
      { path: "/citas", label: "Agendar cita", group: "publico", screen: "calendar" },
      { path: "/ready-to-wear", label: "Ready-to-wear", group: "publico", screen: "store" },
      { path: "/clients/[id]/medidas", label: "Medidas", group: "panel", screen: "form" },
      { path: "/orders/[id]/orden-taller", label: "Orden de taller", group: "operacion", screen: "docs" },
      { path: "/finance/reportes", label: "Reportes", group: "panel", screen: "dashboard" },
    ],
    liveUrl: "https://www.johnhenryoficial.com",
    demoUrl: null,
    brand: { primary: "#c4a55a", secondary: "#e8d090", surface: "#0e1a2b", ink: "#f4efe2", scheme: "dark" },
    screen: "landing",
    metrics: [
      { key: "orders", label: "Órdenes de taller", unit: "órdenes", base: 48, growth: 0.04, form: "bars" },
      { key: "appointments", label: "Citas", unit: "citas", base: 90, growth: 0.05, form: "area" },
    ],
    featured: true,
  },
];
