import type { Project } from "./types";

/** Productos SaaS y plataformas operativas. */
export const productProjects: Project[] = [
  {
    slug: "academyx",
    name: "AcademyX CRM",
    client: "Academias y colegios",
    industry: "Educación y deporte",
    tagline: "ERP multi-institución para academias, colegios y escuelas de fútbol.",
    description:
      "Matrícula en línea, cobros recurrentes con Yappy y PagueloFácil, morosidad, nómina, aula virtual con exámenes y calificaciones, y comunicación con las familias por WhatsApp. Cada institución opera aislada dentro de la misma plataforma, con un superadmin que vigila los crons y los cobros de todas.",
    category: "saas",
    status: "produccion",
    years: [2025, 2026],
    stack: ["Next.js 15", "Supabase", "Cloudflare R2", "Yappy", "PagueloFacil", "WhatsApp", "Brevo", "Recharts"],
    features: [
      "Matrícula en línea con aprobación y bloqueo por mora",
      "Cobros, cuotas, autopago y conciliación bancaria",
      "Dashboard financiero con gastos, nómina y comisiones",
      "Aula virtual: cursos, exámenes, tareas y certificados",
      "Plantillas de correo y notificaciones por WhatsApp",
      "Superadmin multi-academia con panel de crons",
    ],
    routes: [
      { path: "/", label: "Landing", group: "publico", screen: "landing" },
      { path: "/enrollment", label: "Matrícula pública", group: "publico", screen: "form" },
      { path: "/pay/[playerId]", label: "Link de pago", group: "publico", screen: "checkout" },
      { path: "/dashboard", label: "Tablero", group: "panel", screen: "dashboard" },
      { path: "/dashboard/finance", label: "Finanzas", group: "panel", screen: "dashboard" },
      { path: "/dashboard/players", label: "Jugadores", group: "panel", screen: "table" },
      { path: "/teacher/courses", label: "Aula del profesor", group: "operacion", screen: "table" },
      { path: "/student/exams", label: "Exámenes del alumno", group: "operacion", screen: "form" },
      { path: "/superadmin/cron-dashboard", label: "Crons", group: "operacion", screen: "terminal" },
    ],
    liveUrl: "https://academyxcrm.com",
    demoUrl: "/portfolio/demos/academyx",
    brand: { primary: "#2563eb", secondary: "#f59e0b", surface: "#0b1220", ink: "#e5edff", scheme: "dark" },
    screen: "dashboard",
    metrics: [
      { key: "students", label: "Alumnos activos", unit: "alumnos", base: 1400, growth: 0.05, form: "area" },
      { key: "collections", label: "Cobros del mes", unit: "USD", base: 92000, growth: 0.04, form: "bars" },
    ],
    featured: true,
    variants: ["Academyx Schools (variante para colegios)"],
  },
  {
    slug: "uapa-suite",
    name: "UAPA Suite",
    client: "Unión Adventista Panameña",
    industry: "Administración institucional",
    tagline: "Acceso único a los sistemas de la Unión: Secretaría y Visita7.",
    description:
      "Archivo institucional con propiedades, gestión documental con OCR, obreros y vacaciones, organismos con votos numerados e indicadores. Nada se borra: cada cambio deja quién, cuándo y por qué. La autorización se resuelve en base de datos con capacidades por rama de la jerarquía Unión → Campo → iglesia.",
    category: "plataforma",
    status: "produccion",
    years: [2026],
    stack: ["Next.js", "Supabase", "Postgres ltree", "Cloudflare R2", "OCR", "Playwright", "Vitest"],
    features: [
      "Acceso único con segundo factor y códigos de respaldo",
      "Propiedades con carga por lote e índice",
      "Documentos con OCR, cola de procesamiento y revisión",
      "Organismos, sesiones y votos numerados",
      "Asistente de IA que cita la fuente y deja bitácora",
      "Búsqueda global, avisos y vencimientos",
    ],
    routes: [
      { path: "/ingresar", label: "Acceso", group: "publico", screen: "login" },
      { path: "/sistemas", label: "Vestíbulo", group: "panel", screen: "landing" },
      { path: "/secretaria/tablero", label: "Tablero", group: "panel", screen: "dashboard" },
      { path: "/secretaria/propiedades", label: "Propiedades", group: "panel", screen: "table" },
      { path: "/secretaria/documentos", label: "Documentos", group: "panel", screen: "docs" },
      { path: "/secretaria/votos", label: "Votos", group: "operacion", screen: "table" },
      { path: "/secretaria/asistente", label: "Asistente", group: "operacion", screen: "chat" },
    ],
    liveUrl: "https://uapa-suite.vercel.app",
    demoUrl: null,
    brand: { primary: "#cfae5c", secondary: "#7fb0e6", surface: "#09131f", ink: "#faf7f0", scheme: "dark" },
    screen: "docs",
    metrics: [
      { key: "documents", label: "Documentos procesados", unit: "docs", base: 3200, growth: 0.07, form: "bars" },
      { key: "users", label: "Cuentas activas", unit: "cuentas", base: 368, growth: 0.02, form: "area" },
    ],
    featured: true,
  },
  {
    slug: "visita7",
    name: "Visita7",
    client: "Unión Adventista Panameña",
    industry: "Gestión pastoral",
    tagline: "Visitación pastoral sobre la jerarquía real de la Unión, con app móvil.",
    description:
      "Los pastores registran y cierran visitas a familias y miembros; la Unión ve métricas por campo, distrito e iglesia. Importación masiva de familias por lotes, directorio de iglesias geolocalizado, traslados de miembros, libros de oración y calendario. Publicado como PWA y como app nativa con Capacitor.",
    category: "plataforma",
    status: "produccion",
    years: [2023, 2026],
    stack: ["Next.js 16", "Supabase", "Serwist", "Capacitor", "xlsx", "Tailwind v4"],
    features: [
      "Flujo de visita: crear, registrar y cerrar",
      "Importación masiva de familias con seguimiento de jobs",
      "Jerarquía navegable Unión → Campo → distrito → iglesia",
      "Directorio de iglesias con GPS",
      "Traslados, libros de oración y calendario",
      "Papelera con restauración y notificaciones",
    ],
    routes: [
      { path: "/portal", label: "Portal público", group: "publico", screen: "landing" },
      { path: "/dashboard", label: "Tablero", group: "panel", screen: "dashboard" },
      { path: "/visits/create", label: "Nueva visita", group: "operacion", screen: "form" },
      { path: "/families/import", label: "Importar familias", group: "operacion", screen: "table" },
      { path: "/hierarchy", label: "Jerarquía", group: "panel", screen: "table" },
      { path: "/iglesias", label: "Iglesias", group: "panel", screen: "map" },
      { path: "/calendar", label: "Calendario", group: "operacion", screen: "calendar" },
    ],
    liveUrl: "https://visita7-next.vercel.app",
    demoUrl: null,
    brand: { primary: "#62c7b8", secondary: "#cfae5c", surface: "#0f1d2f", ink: "#f2f6f4", scheme: "dark" },
    screen: "map",
    metrics: [
      { key: "visits", label: "Visitas registradas", unit: "visitas", base: 2600, growth: 0.05, form: "bars" },
      { key: "pastors", label: "Pastores activos", unit: "cuentas", base: 340, growth: 0.01, form: "area" },
    ],
    featured: true,
    variants: ["visita7-app (Vue 3, legacy)", "visita-7-api (Python, legacy)"],
  },
  {
    slug: "smart-church",
    name: "Smart Church",
    client: "Iglesias locales",
    industry: "Organizaciones religiosas",
    tagline: "Gestión de una iglesia local: ministerios, cultos, tesorería y citas.",
    description:
      "White-label: clonar el repo y reconfigurar la iglesia produce una instancia nueva. Roster de cultos, setlists de alabanza en tiempo real, modo junta con votación en vivo, CRM de visitas, citas pastorales sincronizadas con Google Calendar y recordatorios automáticos por cron.",
    category: "saas",
    status: "beta",
    years: [2026],
    stack: ["Next.js 16", "Supabase", "Google Calendar", "Serwist", "Brevo", "xlsx"],
    features: [
      "Landing con CMS e inbox de contacto",
      "Ministerios con miembros, eventos y asignaciones",
      "Modo junta con agenda y votación en vivo",
      "Setlists de alabanza en tiempo real",
      "Citas pastorales con Google Calendar y feed .ics",
      "Cron de recordatorios T-7, T-3 y T-1",
    ],
    routes: [
      { path: "/", label: "Landing", group: "publico", screen: "landing" },
      { path: "/agenda-una-cita", label: "Agendar cita", group: "publico", screen: "calendar" },
      { path: "/dashboard", label: "Tablero", group: "panel", screen: "dashboard" },
      { path: "/ministries", label: "Ministerios", group: "panel", screen: "table" },
      { path: "/board/[sessionId]", label: "Junta en vivo", group: "operacion", screen: "chat" },
      { path: "/tesoreria", label: "Tesorería", group: "panel", screen: "dashboard" },
      { path: "/cms", label: "CMS", group: "panel", screen: "docs" },
    ],
    liveUrl: "https://smart-church-liard.vercel.app",
    demoUrl: null,
    brand: { primary: "#ffbd59", secondary: "#f5f0e6", surface: "#040404", ink: "#fbf7ef", scheme: "dark" },
    screen: "calendar",
    metrics: [
      { key: "members", label: "Miembros registrados", unit: "personas", base: 640, growth: 0.03, form: "area" },
      { key: "events", label: "Eventos programados", unit: "eventos", base: 46, growth: 0.04, form: "bars" },
    ],
    featured: true,
  },
  {
    slug: "sembradores",
    name: "Sembradores",
    client: "Iglesias y denominaciones",
    industry: "Organizaciones religiosas",
    tagline: "SaaS multi-tenant para iglesias con contabilidad de doble partida.",
    description:
      "Cada congregación vive en /t/[slug] con su login, branding, dominio y módulos. Personas, hogares, asistencia, ministerios, donaciones con varias pasarelas y contabilidad con plan de cuentas, asientos y períodos. Un panel de plataforma da de alta iglesias y mide uso y suscripción.",
    category: "saas",
    status: "beta",
    years: [2026],
    stack: ["Next.js", "Turborepo", "Supabase", "pgTAP", "Vitest", "Excel import"],
    features: [
      "Onboarding self-service con estado de alta",
      "Runtime por tenant con suspensión y branding",
      "Personas, hogares y redes con importación desde Excel",
      "Donaciones, conciliación y contabilidad completa",
      "Seguimiento pastoral y peticiones de oración",
      "Panel de plataforma con salud del runtime",
    ],
    routes: [
      { path: "/signup", label: "Alta", group: "publico", screen: "form" },
      { path: "/t/[slug]/dashboard", label: "Tablero", group: "panel", screen: "dashboard" },
      { path: "/t/[slug]/people", label: "Personas", group: "panel", screen: "table" },
      { path: "/t/[slug]/accounting/journal-entries", label: "Asientos", group: "operacion", screen: "table" },
      { path: "/t/[slug]/portal", label: "Portal del miembro", group: "publico", screen: "landing" },
      { path: "/churches", label: "Iglesias (plataforma)", group: "operacion", screen: "table" },
    ],
    liveUrl: "https://church-saas.vercel.app",
    demoUrl: "/portfolio/demos/sembradores",
    brand: { primary: "#16a34a", secondary: "#facc15", surface: "#f7f8f5", ink: "#14251a", scheme: "light" },
    screen: "dashboard",
    metrics: [
      { key: "tenants", label: "Iglesias activas", unit: "tenants", base: 22, growth: 0.06, form: "area" },
      { key: "donations", label: "Donaciones", unit: "USD", base: 41000, growth: 0.03, form: "bars" },
    ],
    featured: true,
  },
  {
    slug: "wedding-site",
    name: "Bleidy & Davo",
    client: "Boda privada",
    industry: "Eventos",
    tagline: "Invitación digital, RSVP y control del día para una boda real.",
    description:
      "Nació como el sitio de una boda y terminó siendo la plataforma completa de un solo evento: invitación con RSVP, galería por sub-evento, plano de mesas, control del día, presupuesto, proveedores y comunicaciones por WhatsApp. Fue el origen de Wedding OS.",
    category: "sitio",
    status: "produccion",
    years: [2025, 2026],
    stack: ["Next.js 16", "Supabase", "Resend", "WhatsApp", "dnd-kit", "qrcode", "Recharts"],
    features: [
      "Invitación digital y RSVP público",
      "Galería por evento con subida de medios",
      "Invitados con grupos, importación Excel y QR",
      "Plano de mesas y control del día",
      "Presupuesto, tareas, proveedores y pagos",
      "Bingo de boda para los invitados",
    ],
    routes: [
      { path: "/", label: "Invitación", group: "publico", screen: "landing" },
      { path: "/invite/rsvp", label: "RSVP", group: "publico", screen: "form" },
      { path: "/gallery/[event]", label: "Galería", group: "publico", screen: "store" },
      { path: "/admin/guests", label: "Invitados", group: "panel", screen: "table" },
      { path: "/admin/seating", label: "Mesas", group: "operacion", screen: "map" },
      { path: "/admin/wedding/day-control", label: "Control del día", group: "operacion", screen: "calendar" },
    ],
    liveUrl: "https://www.bleiydavo.com",
    demoUrl: "/portfolio/demos/wedding-site",
    brand: { primary: "#b45309", secondary: "#f5e6c8", surface: "#fffaf3", ink: "#3a2a14", scheme: "light" },
    screen: "landing",
    metrics: [
      { key: "guests", label: "Invitados confirmados", unit: "personas", base: 180, growth: 0.02, form: "area" },
      { key: "photos", label: "Fotos subidas", unit: "fotos", base: 420, growth: 0.1, form: "bars" },
    ],
    featured: true,
    variants: ["Bleixenydavo (línea de tiempo previa, Firebase)"],
  },
  {
    slug: "godmode",
    name: "Godmode",
    client: null,
    industry: "Holding y control de SaaS",
    tagline: "Consola del holding: finanzas de cada negocio y plano de control de los SaaS.",
    description:
      "Desde un solo lugar se cobran y monitorean todos los negocios digitales y concesionarias del grupo. Además funciona como control plane: da de alta tenants, planes, suscripciones y uso de Church SaaS, Wedding OS y AcademyX, y emite enlaces de pago públicos.",
    category: "plataforma",
    status: "interno",
    years: [2026],
    stack: ["Next.js 16", "Supabase", "Server Actions", "Recharts", "Resend", "Dodo Payments"],
    features: [
      "Multi-tenant con RLS por compañía",
      "Empresas, unidades de negocio, socios e inversiones",
      "Suscripciones, cobros recurrentes y puntuales",
      "Inventario automotriz con gastos por unidad",
      "Enlaces de pago públicos",
      "Control plane de tenants externos",
    ],
    routes: [
      { path: "/", label: "Landing", group: "publico", screen: "landing" },
      { path: "/dashboard", label: "Tablero", group: "panel", screen: "dashboard" },
      { path: "/dashboard/companies", label: "Empresas", group: "panel", screen: "table" },
      { path: "/dashboard/vehicles", label: "Vehículos", group: "panel", screen: "store" },
      { path: "/dashboard/analytics", label: "Analítica", group: "panel", screen: "dashboard" },
      { path: "/dashboard/control-plane/tenants", label: "Tenants", group: "operacion", screen: "table" },
      { path: "/pay/[token]", label: "Enlace de pago", group: "publico", screen: "checkout" },
    ],
    liveUrl: "https://godmode-three.vercel.app",
    demoUrl: "/portfolio/demos/godmode",
    brand: { primary: "#22c55e", secondary: "#a3e635", surface: "#07090c", ink: "#e8fbe9", scheme: "dark" },
    screen: "dashboard",
    metrics: [
      { key: "mrr", label: "Ingreso recurrente", unit: "USD", base: 18500, growth: 0.05, form: "area" },
      { key: "tenants", label: "Tenants gobernados", unit: "tenants", base: 27, growth: 0.04, form: "bars" },
    ],
    featured: true,
    variants: ["SAFE STATION/godmode (copia de respaldo)"],
  },
  {
    slug: "cifrapp",
    name: "Cifrapp",
    client: null,
    industry: "Finanzas personales",
    tagline: "Sistema financiero para hogares que responde qué debería pasar después.",
    description:
      "Movimientos, cuentas, tarjetas, presupuestos y metas, más lo que el software de finanzas personales no hace: plan, proyección, escenarios, simulador de deudas y reserva fiscal. Acceso multi-persona por hogar y portal para el contador. Monorepo con app web y admin.",
    category: "saas",
    status: "beta",
    years: [2026],
    stack: ["Next.js", "Turborepo", "Drizzle", "Supabase", "next-intl", "Playwright"],
    features: [
      "Movimientos, cuentas, tarjetas y categorías",
      "Presupuestos, metas y plan con historial",
      "Deudas con simulador y proyección por escenarios",
      "Revisión asistida: duplicados, transferencias, recurrentes",
      "Impuestos y reserva fiscal",
      "Portal del contador con acceso por invitación",
    ],
    routes: [
      { path: "/es", label: "Marketing", group: "publico", screen: "landing" },
      { path: "/es/pricing", label: "Precios", group: "publico", screen: "store" },
      { path: "/es/overview", label: "Resumen", group: "panel", screen: "dashboard" },
      { path: "/es/movements", label: "Movimientos", group: "panel", screen: "table" },
      { path: "/es/projection", label: "Proyección", group: "panel", screen: "dashboard" },
      { path: "/es/debt-simulator", label: "Simulador de deuda", group: "operacion", screen: "form" },
      { path: "/es/access/accountants", label: "Contador", group: "operacion", screen: "table" },
    ],
    liveUrl: "https://norte-web-three.vercel.app",
    demoUrl: null,
    brand: { primary: "#0ea5e9", secondary: "#fbbf24", surface: "#f8fafc", ink: "#0f172a", scheme: "light" },
    screen: "dashboard",
    metrics: [
      { key: "households", label: "Hogares", unit: "hogares", base: 210, growth: 0.08, form: "area" },
      { key: "movements", label: "Movimientos clasificados", unit: "mov.", base: 14000, growth: 0.07, form: "bars" },
    ],
    featured: true,
  },
  {
    slug: "pime-backup",
    name: "Pime Backup Enterprise",
    client: "Grupo GRF",
    industry: "Compliance documental",
    tagline: "Descarga, verifica y certifica la integridad de Google Drive corporativo.",
    description:
      "Los archivos viajan directo entre Google Drive y la computadora del cliente; la nube solo coordina y guarda metadatos. Un agente en Python se instala en Windows, programa jobs y certifica cada descarga. Dashboard web, SDK y CLI en un monorepo.",
    category: "plataforma",
    status: "produccion",
    years: [2026],
    stack: ["Next.js 15", "Supabase", "Python", "FastAPI", "APScheduler", "Turborepo"],
    features: [
      "Agente instalable en Windows con un script",
      "Transferencia directa Drive → máquina del cliente",
      "Verificación y certificación de integridad",
      "Jobs programados con workers dedicados",
      "Doce migraciones SQL con RLS",
      "SDK y CLI propios",
    ],
    routes: [
      { path: "/", label: "Dashboard", group: "panel", screen: "dashboard" },
      { path: "/jobs", label: "Jobs", group: "panel", screen: "table" },
      { path: "/agents", label: "Agentes", group: "operacion", screen: "terminal" },
      { path: "/certificates", label: "Certificados", group: "panel", screen: "docs" },
    ],
    liveUrl: "https://web-ebon-nu-55.vercel.app",
    demoUrl: null,
    brand: { primary: "#0ea5e9", secondary: "#94a3b8", surface: "#0b1220", ink: "#e2eefc", scheme: "dark" },
    screen: "terminal",
    metrics: [
      { key: "gb", label: "GB verificados", unit: "GB", base: 1800, growth: 0.1, form: "bars" },
      { key: "files", label: "Archivos certificados", unit: "archivos", base: 240000, growth: 0.08, form: "area" },
    ],
    featured: true,
  },
];
