import type { Project } from "./types";

/** Productos SaaS y plataformas operativas. */
export const productProjects: Project[] = [
  {
    slug: "academyx",
    name: "AcademyX CRM",
    client: "Academias y colegios",
    industry: "Educación y deporte",
    tagline: "ERP multi-institución para academias, colegios y escuelas de fútbol.",
    description:
      "Matrícula en línea, cobros recurrentes con Yappy y PagueloFácil, morosidad, nómina, aula virtual con exámenes y calificaciones, y comunicación con las familias por WhatsApp. Cada institución opera aislada dentro de la misma plataforma, con un superadmin que vigila los crons y los cobros de todas.",
    category: "saas",
    status: "produccion",
    years: [2025, 2026],
    stack: ["Next.js 15", "Supabase", "Cloudflare R2", "Yappy", "PagueloFacil", "WhatsApp", "Brevo", "Recharts"],
    features: [
      "Matrícula en línea con aprobación y bloqueo por mora",
      "Cobros, cuotas, autopago y conciliación bancaria",
      "Dashboard financiero con gastos, nómina y comisiones",
      "Aula virtual: cursos, exámenes, tareas y certificados",
      "Plantillas de correo y notificaciones por WhatsApp",
      "Superadmin multi-academia con panel de crons",
    ],
    routes: [
      { path: "/", label: "Landing", group: "publico", screen: "landing" },
      { path: "/enrollment", label: "Matrícula pública", group: "publico", screen: "form" },
      { path: "/pay/[playerId]", label: "Link de pago", group: "publico", screen: "checkout" },
      { path: "/dashboard", label: "Tablero", group: "panel", screen: "dashboard" },
      { path: "/dashboard/finance", label: "Finanzas", group: "panel", screen: "dashboard" },
      { path: "/dashboard/players", label: "Jugadores", group: "panel", screen: "table" },
      { path: "/teacher/courses", label: "Aula del profesor", group: "operacion", screen: "table" },
      { path: "/student/exams", label: "Exámenes del alumno", group: "operacion", screen: "form" },
      { path: "/superadmin/cron-dashboard", label: "Crons", group: "operacion", screen: "terminal" },
    ],
    liveUrl: "https://academyxcrm.com",
    demoUrl: "/portfolio/demos/academyx",
    brand: { primary: "#2563eb", secondary: "#f59e0b", surface: "#0b1220", ink: "#e5edff", scheme: "dark" },
    screen: "dashboard",
    metrics: [
      { key: "students", label: "Alumnos activos", unit: "alumnos", base: 1400, growth: 0.05, form: "area" },
      { key: "collections", label: "Cobros del mes", unit: "USD", base: 92000, growth: 0.04, form: "bars" },
    ],
    featured: true,
    variants: ["Academyx Schools (variante para colegios)"],
  },
  {
    slug: "geogenius",
    name: "GeoGenius",
    client: "Colegios y jugadores",
    industry: "Educación gamificada",
    tagline: "Juego de geografía con pasaporte, ligas por aula y CMS para colegios.",
    description:
      "Los alumnos aprenden países y banderas ganando XP, sellos e insignias; los profesores ven el avance de cada aula y las ligas entre clases. Multi-tenant por colegio con facturación, tope de dispositivos y un CMS completo para contenido, testimonios y newsletter. Todo en español e inglés con paridad verificada.",
    category: "saas",
    status: "produccion",
    years: [2026],
    stack: ["Next.js 16", "React 19", "Supabase", "Cloudflare R2", "Framer Motion", "TipTap", "Recharts", "MailerSend"],
    features: [
      "Juego con pistas, mastery normalizado y pasaporte de sellos",
      "Aulas, ligas y dashboards de profesor y alumno",
      "Multi-tenant con aislamiento por colegio y cobro por colegio",
      "CMS de 12 secciones con editor enriquecido",
      "Tope de dispositivos por cuenta",
      "Bilingüe ES/EN con verificación de paridad en CI",
    ],
    routes: [
      { path: "/site/es", label: "Sitio público", group: "publico", screen: "landing" },
      { path: "/site/es/explorador", label: "Explorador", group: "publico", screen: "map" },
      { path: "/schools/panel/jugar", label: "Jugar", group: "operacion", screen: "game" },
      { path: "/schools/panel/liga", label: "Liga", group: "operacion", screen: "table" },
      { path: "/schools/panel/pasaporte", label: "Pasaporte", group: "operacion", screen: "dashboard" },
      { path: "/cms/finanzas", label: "Finanzas", group: "panel", screen: "dashboard" },
      { path: "/cms/contenido", label: "Contenido", group: "panel", screen: "docs" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#d4af37", secondary: "#3b82f6", surface: "#0b1f3a", ink: "#f4ecd2", scheme: "dark" },
    screen: "game",
    metrics: [
      { key: "games", label: "Partidas jugadas", unit: "partidas", base: 18000, growth: 0.09, form: "bars" },
      { key: "schools", label: "Colegios activos", unit: "colegios", base: 14, growth: 0.06, form: "area" },
    ],
    featured: true,
  },
  {
    slug: "uapa-suite",
    name: "UAPA Suite",
    client: "Unión Adventista Panameña",
    industry: "Administración institucional",
    tagline: "Acceso único a los sistemas de la Unión: Secretaría y Visita7.",
    description:
      "Archivo institucional con propiedades, gestión documental con OCR, obreros y vacaciones, organismos con votos numerados e indicadores. Nada se borra: cada cambio deja quién, cuándo y por qué. La autorización se resuelve en base de datos con capacidades por rama de la jerarquía Unión → Campo → iglesia.",
    category: "plataforma",
    status: "produccion",
    years: [2026],
    stack: ["Next.js", "Supabase", "Postgres ltree", "Cloudflare R2", "OCR", "Playwright", "Vitest"],
    features: [
      "Acceso único con segundo factor y códigos de respaldo",
      "Propiedades con carga por lote e índice",
      "Documentos con OCR, cola de procesamiento y revisión",
      "Organismos, sesiones y votos numerados",
      "Asistente de IA que cita la fuente y deja bitácora",
      "Búsqueda global, avisos y vencimientos",
    ],
    routes: [
      { path: "/ingresar", label: "Acceso", group: "publico", screen: "login" },
      { path: "/sistemas", label: "Vestíbulo", group: "panel", screen: "landing" },
      { path: "/secretaria/tablero", label: "Tablero", group: "panel", screen: "dashboard" },
      { path: "/secretaria/propiedades", label: "Propiedades", group: "panel", screen: "table" },
      { path: "/secretaria/documentos", label: "Documentos", group: "panel", screen: "docs" },
      { path: "/secretaria/votos", label: "Votos", group: "operacion", screen: "table" },
      { path: "/secretaria/asistente", label: "Asistente", group: "operacion", screen: "chat" },
    ],
    liveUrl: "https://uapa-suite.vercel.app",
    demoUrl: null,
    brand: { primary: "#cfae5c", secondary: "#7fb0e6", surface: "#09131f", ink: "#faf7f0", scheme: "dark" },
    screen: "docs",
    metrics: [
      { key: "documents", label: "Documentos procesados", unit: "docs", base: 3200, growth: 0.07, form: "bars" },
      { key: "users", label: "Cuentas activas", unit: "cuentas", base: 368, growth: 0.02, form: "area" },
    ],
    featured: true,
  },
  {
    slug: "visita7",
    name: "Visita7",
    client: "Unión Adventista Panameña",
    industry: "Gestión pastoral",
    tagline: "Visitación pastoral sobre la jerarquía real de la Unión, con app móvil.",
    description:
      "Los pastores registran y cierran visitas a familias y miembros; la Unión ve métricas por campo, distrito e iglesia. Importación masiva de familias por lotes, directorio de iglesias geolocalizado, traslados de miembros, libros de oración y calendario. Publicado como PWA y como app nativa con Capacitor.",
    category: "plataforma",
    status: "produccion",
    years: [2023, 2026],
    stack: ["Next.js 16", "Supabase", "Serwist", "Capacitor", "xlsx", "Tailwind v4"],
    features: [
      "Flujo de visita: crear, registrar y cerrar",
      "Importación masiva de familias con seguimiento de jobs",
      "Jerarquía navegable Unión → Campo → distrito → iglesia",
      "Directorio de iglesias con GPS",
      "Traslados, libros de oración y calendario",
      "Papelera con restauración y notificaciones",
    ],
    routes: [
      { path: "/portal", label: "Portal público", group: "publico", screen: "landing" },
      { path: "/dashboard", label: "Tablero", group: "panel", screen: "dashboard" },
      { path: "/visits/create", label: "Nueva visita", group: "operacion", screen: "form" },
      { path: "/families/import", label: "Importar familias", group: "operacion", screen: "table" },
      { path: "/hierarchy", label: "Jerarquía", group: "panel", screen: "table" },
      { path: "/iglesias", label: "Iglesias", group: "panel", screen: "map" },
      { path: "/calendar", label: "Calendario", group: "operacion", screen: "calendar" },
    ],
    liveUrl: "https://visita7-next.vercel.app",
    demoUrl: null,
    brand: { primary: "#62c7b8", secondary: "#cfae5c", surface: "#0f1d2f", ink: "#f2f6f4", scheme: "dark" },
    screen: "map",
    metrics: [
      { key: "visits", label: "Visitas registradas", unit: "visitas", base: 2600, growth: 0.05, form: "bars" },
      { key: "pastors", label: "Pastores activos", unit: "cuentas", base: 340, growth: 0.01, form: "area" },
    ],
    featured: true,
    variants: ["visita7-app (Vue 3, legacy)", "visita-7-api (Python, legacy)"],
  },
  {
    slug: "smart-church",
    name: "Smart Church",
    client: "Iglesias locales",
    industry: "Organizaciones religiosas",
    tagline: "Gestión de una iglesia local: ministerios, cultos, tesorería y citas.",
    description:
      "White-label: clonar el repo y reconfigurar la iglesia produce una instancia nueva. Roster de cultos, setlists de alabanza en tiempo real, modo junta con votación en vivo, CRM de visitas, citas pastorales sincronizadas con Google Calendar y recordatorios automáticos por cron.",
    category: "saas",
    status: "beta",
    years: [2026],
    stack: ["Next.js 16", "Supabase", "Google Calendar", "Serwist", "Brevo", "xlsx"],
    features: [
      "Landing con CMS e inbox de contacto",
      "Ministerios con miembros, eventos y asignaciones",
      "Modo junta con agenda y votación en vivo",
      "Setlists de alabanza en tiempo real",
      "Citas pastorales con Google Calendar y feed .ics",
      "Cron de recordatorios T-7, T-3 y T-1",
    ],
    routes: [
      { path: "/", label: "Landing", group: "publico", screen: "landing" },
      { path: "/agenda-una-cita", label: "Agendar cita", group: "publico", screen: "calendar" },
      { path: "/dashboard", label: "Tablero", group: "panel", screen: "dashboard" },
      { path: "/ministries", label: "Ministerios", group: "panel", screen: "table" },
      { path: "/board/[sessionId]", label: "Junta en vivo", group: "operacion", screen: "chat" },
      { path: "/tesoreria", label: "Tesorería", group: "panel", screen: "dashboard" },
      { path: "/cms", label: "CMS", group: "panel", screen: "docs" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#ffbd59", secondary: "#f5f0e6", surface: "#040404", ink: "#fbf7ef", scheme: "dark" },
    screen: "calendar",
    metrics: [
      { key: "members", label: "Miembros registrados", unit: "personas", base: 640, growth: 0.03, form: "area" },
      { key: "events", label: "Eventos programados", unit: "eventos", base: 46, growth: 0.04, form: "bars" },
    ],
    featured: false,
  },
  {
    slug: "sembradores",
    name: "Sembradores",
    client: "Iglesias y denominaciones",
    industry: "Organizaciones religiosas",
    tagline: "SaaS multi-tenant para iglesias con contabilidad de doble partida.",
    description:
      "Cada congregación vive en /t/[slug] con su login, branding, dominio y módulos. Personas, hogares, asistencia, ministerios, donaciones con varias pasarelas y contabilidad con plan de cuentas, asientos y períodos. Un panel de plataforma da de alta iglesias y mide uso y suscripción.",
    category: "saas",
    status: "beta",
    years: [2026],
    stack: ["Next.js", "Turborepo", "Supabase", "pgTAP", "Vitest", "Excel import"],
    features: [
      "Onboarding self-service con estado de alta",
      "Runtime por tenant con suspensión y branding",
      "Personas, hogares y redes con importación desde Excel",
      "Donaciones, conciliación y contabilidad completa",
      "Seguimiento pastoral y peticiones de oración",
      "Panel de plataforma con salud del runtime",
    ],
    routes: [
      { path: "/signup", label: "Alta", group: "publico", screen: "form" },
      { path: "/t/[slug]/dashboard", label: "Tablero", group: "panel", screen: "dashboard" },
      { path: "/t/[slug]/people", label: "Personas", group: "panel", screen: "table" },
      { path: "/t/[slug]/accounting/journal-entries", label: "Asientos", group: "operacion", screen: "table" },
      { path: "/t/[slug]/portal", label: "Portal del miembro", group: "publico", screen: "landing" },
      { path: "/churches", label: "Iglesias (plataforma)", group: "operacion", screen: "table" },
    ],
    liveUrl: null,
    demoUrl: "/portfolio/demos/sembradores",
    brand: { primary: "#16a34a", secondary: "#facc15", surface: "#f7f8f5", ink: "#14251a", scheme: "light" },
    screen: "dashboard",
    metrics: [
      { key: "tenants", label: "Iglesias activas", unit: "tenants", base: 22, growth: 0.06, form: "area" },
      { key: "donations", label: "Donaciones", unit: "USD", base: 41000, growth: 0.03, form: "bars" },
    ],
    featured: true,
  },
  {
    slug: "church-translate",
    name: "Church Translate",
    client: "Iglesias multiculturales",
    industry: "Traducción en vivo",
    tagline: "Subtítulos traducidos en tiempo real para servicios religiosos.",
    description:
      "El pastor habla en español y los asistentes leen la traducción en inglés o portugués en una pantalla pública sin iniciar sesión. Consola de operador por evento, glosario por organización que alimenta el contexto y exportación de transcripciones a DOCX y PDF. Motor de STT y traducción intercambiable.",
    category: "saas",
    status: "beta",
    years: [2026],
    stack: ["Next.js 15", "Supabase Realtime", "Gemini 2.5", "TanStack Query", "react-pdf", "docx"],
    features: [
      "Consola de operador en vivo por evento",
      "Pantalla pública por idioma sin login",
      "Segmentación de frases y glosario por organización",
      "Fondos personalizables para proyección",
      "Multi-tenant por organización con onboarding",
      "Exportación de transcripciones a DOCX y PDF",
    ],
    routes: [
      { path: "/display/[event]/en", label: "Pantalla pública", group: "publico", screen: "chat" },
      { path: "/operator/[eventId]", label: "Operador", group: "operacion", screen: "terminal" },
      { path: "/[org]/events", label: "Eventos", group: "panel", screen: "table" },
      { path: "/[org]/settings/glossary", label: "Glosario", group: "panel", screen: "docs" },
      { path: "/onboarding", label: "Onboarding", group: "publico", screen: "form" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#8b5cf6", secondary: "#22d3ee", surface: "#0a0a0f", ink: "#f3f0ff", scheme: "dark" },
    screen: "chat",
    metrics: [
      { key: "minutes", label: "Minutos traducidos", unit: "min", base: 5400, growth: 0.08, form: "bars" },
      { key: "viewers", label: "Espectadores por evento", unit: "personas", base: 120, growth: 0.03, form: "area" },
    ],
    featured: false,
  },
  {
    slug: "wedding-os",
    name: "Wedding OS",
    client: "Wedding planners",
    industry: "Eventos",
    tagline: "SaaS para planners: cada boda, pareja e invitado con su propio acceso.",
    description:
      "Tres portales sobre la misma base: el planner administra su cartera, la pareja sigue presupuesto, tareas y plano de mesas, y el invitado confirma asistencia con un enlace. Suscripciones, planes y medición de uso se gobiernan desde un super-admin. Internacionalizado por locale.",
    category: "saas",
    status: "beta",
    years: [2026],
    stack: ["Next.js 16", "Supabase", "next-intl", "dnd-kit", "Serwist", "WhatsApp"],
    features: [
      "Multi-tenant planner → boda → pareja → invitado",
      "Suscripciones, planes, paquetes y uso",
      "Presupuesto, tareas, timeline y proveedores",
      "Plano de mesas con arrastrar y soltar",
      "RSVP con activación por token",
      "Invitación pública y vista en vivo del evento",
    ],
    routes: [
      { path: "/es/planner", label: "Portal planner", group: "panel", screen: "dashboard" },
      { path: "/es/planner/weddings/[id]/tasks", label: "Tareas", group: "panel", screen: "table" },
      { path: "/es/couple/weddings/[id]/seating", label: "Plano de mesas", group: "operacion", screen: "map" },
      { path: "/es/guest/weddings/[id]/rsvp", label: "RSVP", group: "publico", screen: "form" },
      { path: "/es/invite/[slug]", label: "Invitación", group: "publico", screen: "landing" },
      { path: "/es/super/saas/plans", label: "Planes", group: "operacion", screen: "table" },
    ],
    liveUrl: null,
    demoUrl: "/portfolio/demos/wedding-saas",
    brand: { primary: "#e11d48", secondary: "#d4a373", surface: "#fdf8f5", ink: "#2a1a1f", scheme: "light" },
    screen: "dashboard",
    metrics: [
      { key: "weddings", label: "Bodas activas", unit: "bodas", base: 38, growth: 0.07, form: "area" },
      { key: "rsvp", label: "Confirmaciones", unit: "RSVP", base: 900, growth: 0.06, form: "bars" },
    ],
    featured: false,
  },
  {
    slug: "wedding-site",
    name: "Bleidy & Davo",
    client: "Boda privada",
    industry: "Eventos",
    tagline: "Invitación digital, RSVP y control del día para una boda real.",
    description:
      "Nació como el sitio de una boda y terminó siendo la plataforma completa de un solo evento: invitación con RSVP, galería por sub-evento, plano de mesas, control del día, presupuesto, proveedores y comunicaciones por WhatsApp. Fue el origen de Wedding OS.",
    category: "sitio",
    status: "produccion",
    years: [2025, 2026],
    stack: ["Next.js 16", "Supabase", "Resend", "WhatsApp", "dnd-kit", "qrcode", "Recharts"],
    features: [
      "Invitación digital y RSVP público",
      "Galería por evento con subida de medios",
      "Invitados con grupos, importación Excel y QR",
      "Plano de mesas y control del día",
      "Presupuesto, tareas, proveedores y pagos",
      "Bingo de boda para los invitados",
    ],
    routes: [
      { path: "/", label: "Invitación", group: "publico", screen: "landing" },
      { path: "/invite/rsvp", label: "RSVP", group: "publico", screen: "form" },
      { path: "/gallery/[event]", label: "Galería", group: "publico", screen: "store" },
      { path: "/admin/guests", label: "Invitados", group: "panel", screen: "table" },
      { path: "/admin/seating", label: "Mesas", group: "operacion", screen: "map" },
      { path: "/admin/wedding/day-control", label: "Control del día", group: "operacion", screen: "calendar" },
    ],
    liveUrl: "https://www.bleiydavo.com",
    demoUrl: "/portfolio/demos/wedding-site",
    brand: { primary: "#b45309", secondary: "#f5e6c8", surface: "#fffaf3", ink: "#3a2a14", scheme: "light" },
    screen: "landing",
    metrics: [
      { key: "guests", label: "Invitados confirmados", unit: "personas", base: 180, growth: 0.02, form: "area" },
      { key: "photos", label: "Fotos subidas", unit: "fotos", base: 420, growth: 0.1, form: "bars" },
    ],
    featured: false,
    variants: ["Bleixenydavo (línea de tiempo previa, Firebase)"],
  },
  {
    slug: "godmode",
    name: "Godmode",
    client: null,
    industry: "Holding y control de SaaS",
    tagline: "Consola del holding: finanzas de cada negocio y plano de control de los SaaS.",
    description:
      "Desde un solo lugar se cobran y monitorean todos los negocios digitales y concesionarias del grupo. Además funciona como control plane: da de alta tenants, planes, suscripciones y uso de Church SaaS, Wedding OS y AcademyX, y emite enlaces de pago públicos.",
    category: "plataforma",
    status: "interno",
    years: [2026],
    stack: ["Next.js 16", "Supabase", "Server Actions", "Recharts", "Resend", "Dodo Payments"],
    features: [
      "Multi-tenant con RLS por compañía",
      "Empresas, unidades de negocio, socios e inversiones",
      "Suscripciones, cobros recurrentes y puntuales",
      "Inventario automotriz con gastos por unidad",
      "Enlaces de pago públicos",
      "Control plane de tenants externos",
    ],
    routes: [
      { path: "/", label: "Landing", group: "publico", screen: "landing" },
      { path: "/dashboard", label: "Tablero", group: "panel", screen: "dashboard" },
      { path: "/dashboard/companies", label: "Empresas", group: "panel", screen: "table" },
      { path: "/dashboard/vehicles", label: "Vehículos", group: "panel", screen: "store" },
      { path: "/dashboard/analytics", label: "Analítica", group: "panel", screen: "dashboard" },
      { path: "/dashboard/control-plane/tenants", label: "Tenants", group: "operacion", screen: "table" },
      { path: "/pay/[token]", label: "Enlace de pago", group: "publico", screen: "checkout" },
    ],
    liveUrl: "https://godmode-three.vercel.app",
    demoUrl: "/portfolio/demos/godmode",
    brand: { primary: "#22c55e", secondary: "#a3e635", surface: "#07090c", ink: "#e8fbe9", scheme: "dark" },
    screen: "dashboard",
    metrics: [
      { key: "mrr", label: "Ingreso recurrente", unit: "USD", base: 18500, growth: 0.05, form: "area" },
      { key: "tenants", label: "Tenants gobernados", unit: "tenants", base: 27, growth: 0.04, form: "bars" },
    ],
    featured: true,
    variants: ["SAFE STATION/godmode (copia de respaldo)"],
  },
  {
    slug: "cifrapp",
    name: "Cifrapp",
    client: null,
    industry: "Finanzas personales",
    tagline: "Sistema financiero para hogares que responde qué debería pasar después.",
    description:
      "Movimientos, cuentas, tarjetas, presupuestos y metas, más lo que el software de finanzas personales no hace: plan, proyección, escenarios, simulador de deudas y reserva fiscal. Acceso multi-persona por hogar y portal para el contador. Monorepo con app web y admin.",
    category: "saas",
    status: "beta",
    years: [2026],
    stack: ["Next.js", "Turborepo", "Drizzle", "Supabase", "next-intl", "Playwright"],
    features: [
      "Movimientos, cuentas, tarjetas y categorías",
      "Presupuestos, metas y plan con historial",
      "Deudas con simulador y proyección por escenarios",
      "Revisión asistida: duplicados, transferencias, recurrentes",
      "Impuestos y reserva fiscal",
      "Portal del contador con acceso por invitación",
    ],
    routes: [
      { path: "/es", label: "Marketing", group: "publico", screen: "landing" },
      { path: "/es/pricing", label: "Precios", group: "publico", screen: "store" },
      { path: "/es/overview", label: "Resumen", group: "panel", screen: "dashboard" },
      { path: "/es/movements", label: "Movimientos", group: "panel", screen: "table" },
      { path: "/es/projection", label: "Proyección", group: "panel", screen: "dashboard" },
      { path: "/es/debt-simulator", label: "Simulador de deuda", group: "operacion", screen: "form" },
      { path: "/es/access/accountants", label: "Contador", group: "operacion", screen: "table" },
    ],
    liveUrl: "https://norte-web-three.vercel.app",
    demoUrl: null,
    brand: { primary: "#0ea5e9", secondary: "#fbbf24", surface: "#f8fafc", ink: "#0f172a", scheme: "light" },
    screen: "dashboard",
    metrics: [
      { key: "households", label: "Hogares", unit: "hogares", base: 210, growth: 0.08, form: "area" },
      { key: "movements", label: "Movimientos clasificados", unit: "mov.", base: 14000, growth: 0.07, form: "bars" },
    ],
    featured: false,
  },
  {
    slug: "tdp",
    name: "TDP Ticketing",
    client: "Transporte terrestre",
    industry: "Transporte",
    tagline: "Boletos de bus en línea, POS de doble pantalla y flota con GPS.",
    description:
      "Portal público de venta, terminales POS con pantalla para el cliente empaquetadas en Electron, escáner QR de abordaje, pantallas de salidas y tracking GPS en vivo. Cinco pasarelas panameñas: Yappy, PagueloFácil, Tilopay, PayU y Banesco.",
    category: "plataforma",
    status: "beta",
    years: [2025],
    stack: ["Next.js 14", "Electron", "Supabase Realtime", "Yappy", "PagueloFacil", "Tilopay", "QR", "PWA"],
    features: [
      "Búsqueda y compra de boletos web y móvil",
      "POS con pantalla secundaria para el cliente",
      "Escáner QR de abordaje con validación firmada",
      "Buses, rutas, horarios y asientos en tiempo real",
      "Tracking GPS y pantallas de salidas",
      "Configuración fiscal, impresora térmica y lealtad",
    ],
    routes: [
      { path: "/search", label: "Buscar viaje", group: "publico", screen: "store" },
      { path: "/checkout", label: "Pago", group: "publico", screen: "checkout" },
      { path: "/pos/[terminalId]", label: "Terminal POS", group: "operacion", screen: "checkout" },
      { path: "/scanner", label: "Escáner", group: "movil", screen: "game" },
      { path: "/displays/departures", label: "Pantalla de salidas", group: "operacion", screen: "table" },
      { path: "/dashboard/control-center", label: "Centro de control", group: "panel", screen: "map" },
      { path: "/dashboard/routes", label: "Rutas", group: "panel", screen: "table" },
    ],
    liveUrl: null,
    demoUrl: "/portfolio/demos/tdp",
    brand: { primary: "#0066cc", secondary: "#ffd60a", surface: "#f4f7fb", ink: "#0b1a33", scheme: "light" },
    screen: "map",
    metrics: [
      { key: "tickets", label: "Boletos vendidos", unit: "boletos", base: 26000, growth: 0.04, form: "bars" },
      { key: "buses", label: "Buses en ruta", unit: "buses", base: 48, growth: 0.02, form: "area" },
    ],
    featured: true,
  },
  {
    slug: "tickets",
    name: "Tickets Platform",
    client: "Productoras de eventos",
    industry: "Entretenimiento",
    tagline: "Entradas con QR firmado y pagos cashless con manillas NFC.",
    description:
      "Plataforma re-brandeable dimensionada para más de 50.000 transacciones diarias: temas versionados desde base de datos, pasarelas intercambiables, QR firmados criptográficamente, wallet cashless, PWA de escaneo offline y auditoría completa de accesos y dinero.",
    category: "plataforma",
    status: "prototipo",
    years: [2025],
    stack: ["Next.js 14", "Drizzle ORM", "Supabase", "jose", "NFC", "IndexedDB", "Brevo"],
    features: [
      "Theming desde base de datos con versiones",
      "Pasarelas: Yappy, PagueloFácil y transferencia",
      "QR firmados criptográficamente",
      "Wallet cashless y control de acceso NFC",
      "RBAC con roles, permisos y constraints",
      "Escáner PWA con soporte offline",
    ],
    routes: [
      { path: "/events/[slug]", label: "Evento", group: "publico", screen: "landing" },
      { path: "/events/[slug]/checkout", label: "Compra", group: "publico", screen: "checkout" },
      { path: "/profile/wallet", label: "Wallet", group: "publico", screen: "dashboard" },
      { path: "/admin/scanner", label: "Escáner", group: "movil", screen: "game" },
      { path: "/admin/nfc/bind", label: "Vincular NFC", group: "operacion", screen: "form" },
      { path: "/super/themes", label: "Temas", group: "operacion", screen: "docs" },
      { path: "/super/audit/logs", label: "Auditoría", group: "operacion", screen: "terminal" },
    ],
    liveUrl: null,
    demoUrl: "/portfolio/demos/tickets",
    brand: { primary: "#f43f5e", secondary: "#a78bfa", surface: "#0c0a12", ink: "#fbe9ee", scheme: "dark" },
    screen: "checkout",
    metrics: [
      { key: "sales", label: "Entradas vendidas", unit: "entradas", base: 31000, growth: 0.06, form: "bars" },
      { key: "cashless", label: "Consumo cashless", unit: "USD", base: 58000, growth: 0.05, form: "area" },
    ],
    featured: false,
  },
  {
    slug: "medsuite",
    name: "MedSuite",
    client: "Clínicas y consultorios",
    industry: "Salud",
    tagline: "Gestión de clínicas white-label: un archivo de configuración por cliente.",
    description:
      "Cada clínica recibe su propio despliegue clonado; marca, copy, colores, contactos y features se controlan desde un único archivo. Sitio público con reserva de citas y reglas de cancelación por token en el correo, más un panel con pacientes, doctores, servicios y horarios.",
    category: "saas",
    status: "prototipo",
    years: [2026],
    stack: ["Next.js 16", "Supabase", "Brevo", "react-pdf", "date-fns", "Zod"],
    features: [
      "Configuración de cliente en un solo archivo",
      "Reserva pública con ventana y reglas de cancelación",
      "Confirmación y cancelación por token en el email",
      "CRM de pacientes con ficha clínica",
      "Doctores, servicios y horarios",
      "PDF de citas y documentos",
    ],
    routes: [
      { path: "/", label: "Sitio de la clínica", group: "publico", screen: "landing" },
      { path: "/appointments/confirm/[token]", label: "Confirmar cita", group: "publico", screen: "form" },
      { path: "/admin", label: "Panel", group: "panel", screen: "dashboard" },
      { path: "/admin/patients", label: "Pacientes", group: "panel", screen: "table" },
      { path: "/admin/appointments", label: "Agenda", group: "operacion", screen: "calendar" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#1c3a2f", secondary: "#9fc5b2", surface: "#eaf0ed", ink: "#111917", scheme: "light" },
    screen: "calendar",
    metrics: [
      { key: "appointments", label: "Citas agendadas", unit: "citas", base: 520, growth: 0.05, form: "bars" },
      { key: "patients", label: "Pacientes", unit: "personas", base: 1100, growth: 0.03, form: "area" },
    ],
    featured: false,
  },
  {
    slug: "house-booking",
    name: "Reserva Directa",
    client: "Propietarios de alquiler vacacional",
    industry: "Hospitalidad",
    tagline: "Reservas sin comisión de plataforma, sincronizadas con Airbnb por iCal.",
    description:
      "Sistema white-label multi-tenant para propietarios de alquiler de corto plazo: sitio público por propiedad con galería y calendario, flujo de reserva con confirmación, CMS privado, sincronización iCal con Airbnb y pagos vía Yappy y banca panameña.",
    category: "saas",
    status: "prototipo",
    years: [2026],
    stack: ["Next.js 15", "Supabase", "ical.js", "Cloudflare R2", "Yappy", "Brevo"],
    features: [
      "Sitio público por propiedad con calendario",
      "Reserva con confirmación y correo transaccional",
      "CMS por propietario: propiedades, disponibilidad, leads",
      "Sincronización iCal con Airbnb",
      "Temas por tenant",
      "Pagos con Yappy y banca panameña",
    ],
    routes: [
      { path: "/propiedades/[slug]", label: "Propiedad", group: "publico", screen: "store" },
      { path: "/reservar/[slug]", label: "Reservar", group: "publico", screen: "checkout" },
      { path: "/cms", label: "Panel", group: "panel", screen: "dashboard" },
      { path: "/cms/disponibilidad/[id]", label: "Disponibilidad", group: "operacion", screen: "calendar" },
      { path: "/cms/reservas", label: "Reservas", group: "panel", screen: "table" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#1b4332", secondary: "#b8960c", surface: "#fafaf8", ink: "#1a1f1b", scheme: "light" },
    screen: "store",
    metrics: [
      { key: "nights", label: "Noches reservadas", unit: "noches", base: 260, growth: 0.06, form: "bars" },
      { key: "occupancy", label: "Ocupación", unit: "%", base: 62, growth: 0.01, form: "area" },
    ],
    featured: false,
  },
  {
    slug: "pime-backup",
    name: "Pime Backup Enterprise",
    client: "Grupo GRF",
    industry: "Compliance documental",
    tagline: "Descarga, verifica y certifica la integridad de Google Drive corporativo.",
    description:
      "Los archivos viajan directo entre Google Drive y la computadora del cliente; la nube solo coordina y guarda metadatos. Un agente en Python se instala en Windows, programa jobs y certifica cada descarga. Dashboard web, SDK y CLI en un monorepo.",
    category: "plataforma",
    status: "produccion",
    years: [2026],
    stack: ["Next.js 15", "Supabase", "Python", "FastAPI", "APScheduler", "Turborepo"],
    features: [
      "Agente instalable en Windows con un script",
      "Transferencia directa Drive → máquina del cliente",
      "Verificación y certificación de integridad",
      "Jobs programados con workers dedicados",
      "Doce migraciones SQL con RLS",
      "SDK y CLI propios",
    ],
    routes: [
      { path: "/", label: "Dashboard", group: "panel", screen: "dashboard" },
      { path: "/jobs", label: "Jobs", group: "panel", screen: "table" },
      { path: "/agents", label: "Agentes", group: "operacion", screen: "terminal" },
      { path: "/certificates", label: "Certificados", group: "panel", screen: "docs" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#0ea5e9", secondary: "#94a3b8", surface: "#0b1220", ink: "#e2eefc", scheme: "dark" },
    screen: "terminal",
    metrics: [
      { key: "gb", label: "GB verificados", unit: "GB", base: 1800, growth: 0.1, form: "bars" },
      { key: "files", label: "Archivos certificados", unit: "archivos", base: 240000, growth: 0.08, form: "area" },
    ],
    featured: false,
  },
  {
    slug: "pime-social",
    name: "Pime Social AI",
    client: null,
    industry: "Marketing digital",
    tagline: "Copies con Claude, imágenes con DALL·E y publicación automática en Instagram.",
    description:
      "Genera el texto de cada publicación con Claude y la imagen con DALL·E 3, las programa en una cola y las publica en Instagram vía Graph API con tokens de larga duración renovables. Analítica de rendimiento por publicación e integración con OpenClaw como capa de agente.",
    category: "herramienta",
    status: "beta",
    years: [2026],
    stack: ["Next.js 15", "Claude API", "OpenAI Images", "Instagram Graph API", "Supabase", "Recharts"],
    features: [
      "Generación de copies con Claude",
      "Imágenes con DALL·E 3 guardadas en Storage",
      "Cola de posts programados con publicación automática",
      "OAuth de Instagram y renovación de tokens",
      "Analítica por publicación",
      "Vista de agente OpenClaw",
    ],
    routes: [
      { path: "/posts", label: "Cola de posts", group: "panel", screen: "table" },
      { path: "/posts/[id]", label: "Post", group: "panel", screen: "form" },
      { path: "/analytics", label: "Analítica", group: "panel", screen: "dashboard" },
      { path: "/openclaw", label: "Agente", group: "operacion", screen: "chat" },
      { path: "/api/instagram/callback", label: "OAuth", group: "api", screen: "terminal" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#ec4899", secondary: "#f97316", surface: "#0f0a12", ink: "#fde7f3", scheme: "dark" },
    screen: "chat",
    metrics: [
      { key: "posts", label: "Publicaciones", unit: "posts", base: 60, growth: 0.05, form: "bars" },
      { key: "reach", label: "Alcance", unit: "cuentas", base: 12000, growth: 0.09, form: "area" },
    ],
    featured: false,
    variants: ["Open Claw / Social media pime"],
  },
];
