import type { Project } from "./types";

/** Sistemas en Google Sheets y herramientas internas. */
export const toolProjects: Project[] = [
  {
    slug: "futbol-control",
    name: "Control de Fútbol",
    client: "Academias de fútbol",
    industry: "Deporte formativo",
    tagline: "Gestión de academia en Google Sheets que creció a web-app con pagos.",
    description:
      "Jugadores, familias con descuento, categorías por año, pagos y torneos dentro del Spreadsheet, más una web-app con matrícula pública, link de pago con PagueloFácil y Yappy, cola de correos con tracking y scripts de instalación por cliente. Producto replicable.",
    category: "legacy",
    status: "produccion",
    years: [2025, 2026],
    stack: ["Apps Script", "Google Sheets", "Next.js 15", "Supabase", "PagueloFacil", "Yappy", "Brevo"],
    features: [
      "Jugadores, familias y categorías automáticas",
      "Matrículas, mensualidades, torneos y gastos",
      "Formulario público de matrícula y link de pago",
      "Motor de correos con cola y tracking",
      "Historial, exportadores y manual embebido",
      "Instalación validada por cliente",
    ],
    routes: [
      { path: "Dashboard.html", label: "Tablero", group: "panel", screen: "sheet" },
      { path: "PlayersManager.html", label: "Jugadores", group: "panel", screen: "table" },
      { path: "FinancialDashboard.html", label: "Finanzas", group: "panel", screen: "dashboard" },
      { path: "TournamentManagerWindow", label: "Torneos", group: "operacion", screen: "table" },
      { path: "/enrollment", label: "Matrícula web", group: "publico", screen: "form" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#15803d", secondary: "#facc15", surface: "#f6f8f6", ink: "#14261a", scheme: "light" },
    screen: "sheet",
    metrics: [
      { key: "players", label: "Jugadores", unit: "jugadores", base: 260, growth: 0.03, form: "area" },
      { key: "fees", label: "Mensualidades cobradas", unit: "USD", base: 28000, growth: 0.02, form: "bars" },
    ],
    featured: false,
    variants: ["V2 (repositorio Apps Script)", "backup/V2 (instantánea)"],
  },
  {
    slug: "academia-suarez",
    name: "Academia Suárez",
    client: "Academia Suárez",
    industry: "Deporte formativo",
    tagline: "Primer sistema de academia dentro de Google Sheets, con aprobaciones por formulario.",
    description:
      "Registro de jugadores con categoría automática por edad, grupos familiares con descuento del 15 %, movimientos financieros, aprobaciones pendientes desde Google Forms, buscador y validaciones. Dos generaciones: la original en JavaScript y el refactor versionado en Git.",
    category: "legacy",
    status: "legacy",
    years: [2025],
    stack: ["Apps Script", "Google Sheets", "Google Forms", "clasp"],
    features: [
      "Once categorías por año y género",
      "Grupos familiares con descuento",
      "Aprobaciones desde Google Forms",
      "Buscador y sistema de validaciones",
      "Pruebas automatizadas del script",
    ],
    routes: [
      { path: "Dashboard.html", label: "Tablero", group: "panel", screen: "sheet" },
      { path: "PendingApprovals.html", label: "Aprobaciones", group: "operacion", screen: "table" },
      { path: "FamilyGroupsManager.html", label: "Familias", group: "panel", screen: "table" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#1d4ed8", secondary: "#f59e0b", surface: "#f8fafc", ink: "#0f172a", scheme: "light" },
    screen: "sheet",
    metrics: [
      { key: "players", label: "Jugadores", unit: "jugadores", base: 140, growth: 0.02, form: "area" },
      { key: "approvals", label: "Aprobaciones", unit: "solicitudes", base: 18, growth: 0.03, form: "bars" },
    ],
    featured: false,
    variants: ["Academia Suarez (v1, .js)", "Sistema-Academia-Suarez (v2, .gs)"],
  },
  {
    slug: "sd-autosales",
    name: "SD Auto Sales",
    client: "Sara & Davo",
    industry: "Compraventa de vehículos",
    tagline: "Ganancia real por auto y por socio, dentro de un Spreadsheet.",
    description:
      "Cada auto registra quién aportó capital, los gastos asociados y el precio de venta; el sistema reparte la ganancia neta y el ROI entre socios. Timeline cronológico, balance y gráficas automáticas.",
    category: "legacy",
    status: "produccion",
    years: [2025],
    stack: ["Apps Script", "Google Sheets"],
    features: [
      "Socios con capital disponible",
      "Inversión de compra repartida entre socios",
      "Gastos por auto con atribución",
      "Ganancia neta y ROI por socio",
      "Gráficas de ventas y balance",
    ],
    routes: [
      { path: "MainPage", label: "Timeline", group: "panel", screen: "sheet" },
      { path: "CarProfile", label: "Ficha del auto", group: "panel", screen: "form" },
      { path: "BalancePage", label: "Balance", group: "panel", screen: "dashboard" },
      { path: "ChartsPage", label: "Gráficas", group: "panel", screen: "dashboard" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#dc2626", secondary: "#fbbf24", surface: "#fafafa", ink: "#1c1917", scheme: "light" },
    screen: "sheet",
    metrics: [
      { key: "cars", label: "Autos vendidos", unit: "autos", base: 6, growth: 0.04, form: "bars" },
      { key: "roi", label: "ROI acumulado", unit: "%", base: 18, growth: 0.02, form: "area" },
    ],
    featured: false,
    variants: ["sd-autosales (carpeta reservada para la versión web)"],
  },
  {
    slug: "git-pime",
    name: "Git-PIME",
    client: null,
    industry: "Tooling interno",
    tagline: "Una identidad de GitHub y de Vercel por proyecto, sin publicar con la cuenta equivocada.",
    description:
      "CLI y portal local que aplica perfil, llave SSH, alias de host y firma de commits por repositorio, envuelve commit y push, verifica sincronía con el remoto y valida Vercel y Supabase antes de desplegar. Administra los MCP por proyecto con credenciales fuera de todo repo.",
    category: "herramienta",
    status: "interno",
    years: [2026],
    stack: ["Node.js", "ESM", "node:test", "Sin dependencias"],
    features: [
      "Perfiles de identidad por repo: apply, verify, doctor",
      "Funnel de commit y push firmado",
      "Portal web en localhost:3847",
      "Preflight de identidad, Vercel, Supabase y git",
      "MCP por proyecto con permisos 0600",
      "Instalador para macOS",
    ],
    routes: [
      { path: "localhost:3847", label: "Portal", group: "panel", screen: "table" },
      { path: "pime-git menu", label: "Menú de terminal", group: "operacion", screen: "terminal" },
      { path: "pime-git preflight", label: "Preflight", group: "operacion", screen: "terminal" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#f97316", secondary: "#38bdf8", surface: "#0a0a0a", ink: "#fff3e8", scheme: "dark" },
    screen: "terminal",
    metrics: [
      { key: "pushes", label: "Pushes verificados", unit: "pushes", base: 320, growth: 0.05, form: "bars" },
      { key: "repos", label: "Repos gobernados", unit: "repos", base: 28, growth: 0.03, form: "area" },
    ],
    featured: false,
  },
  {
    slug: "cajon-revelado",
    name: "Cajón Revelado",
    client: null,
    industry: "Componentes",
    tagline: "Menú móvil que no se superpone: la página se encoge y revela lo de abajo.",
    description:
      "Componente React desacoplado de UAPA Suite. El menú vive siempre debajo a pantalla completa; lo que se mueve es la página, que se redondea y deja una franja visible para volver con un toque. CSS plano, sin Tailwind, agnóstico de enrutador.",
    category: "herramienta",
    status: "interno",
    years: [2026],
    stack: ["React", "CSS", "Next.js adapter"],
    features: [
      "Animación de revelado con la página como actor",
      "Una sola peer dependency",
      "Adaptador de dos líneas para App Router",
      "Ejemplo con secciones agrupadas",
    ],
    routes: [
      { path: "CajonRevelado.tsx", label: "Componente", group: "operacion", screen: "docs" },
      { path: "ejemplo/App.tsx", label: "Ejemplo", group: "publico", screen: "landing" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#14213a", secondary: "#cfae5c", surface: "#faf7f0", ink: "#14213a", scheme: "light" },
    screen: "landing",
    metrics: [
      { key: "installs", label: "Proyectos que lo usan", unit: "proyectos", base: 3, growth: 0.05, form: "bars" },
      { key: "fps", label: "Fluidez", unit: "fps", base: 60, growth: 0, form: "area" },
    ],
    featured: false,
  },
  {
    slug: "integraciones-panama",
    name: "Integraciones Panamá",
    client: null,
    industry: "Pagos y facturación",
    tagline: "Base de conocimiento de Yappy, PagueloFácil, factura electrónica y Cloudflare R2.",
    description:
      "Manuales, swagger, colecciones Postman y ejemplos JSON que se reutilizan en cada producto que cobra en Panamá: Yappy por API y web component, Yappy en caja, factura electrónica con consumidor final, gobierno, extranjero y notas de crédito, y un helper de R2.",
    category: "herramienta",
    status: "interno",
    years: [2025, 2026],
    stack: ["Yappy", "PagueloFacil", "e-Factura", "Cloudflare R2", "OpenAPI", "Postman"],
    features: [
      "Manual de integración de APIs Yappy y web component",
      "Integración de Yappy en cajas físicas",
      "Swagger de factura electrónica con ocho ejemplos",
      "Helper de R2 para objetos, carpetas y ZIP",
    ],
    routes: [
      { path: "yappy/swagger.yml", label: "API Yappy", group: "api", screen: "docs" },
      { path: "facturacion/swagger.json", label: "e-Factura", group: "api", screen: "docs" },
      { path: "r2Manager.py", label: "R2", group: "api", screen: "terminal" },
    ],
    liveUrl: null,
    demoUrl: null,
    brand: { primary: "#0ea5e9", secondary: "#22c55e", surface: "#0b1220", ink: "#e2f4ff", scheme: "dark" },
    screen: "docs",
    metrics: [
      { key: "products", label: "Productos que integran", unit: "productos", base: 9, growth: 0.04, form: "bars" },
      { key: "gateways", label: "Pasarelas documentadas", unit: "pasarelas", base: 6, growth: 0, form: "area" },
    ],
    featured: false,
  },
];
